version: '3'

services:

    vuejs:
        container_name: vuejs-v-model
        build: ./containers/local/vuejsdocker/vuejs
        volumes:
            - .:/app
        tty: true
        ports:
            - "8091:8080"
